language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install gfortran liblapack-dev python-scipy libblas-dev
install: 
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  - pip install Cython
  - pip install argparse
  - pip install pandas
  - pip install --no-deps pymc
  - pip install --no-deps kabuki
  - python setup.py build_ext --inplace
script: nosetests
