language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install python python-dev python-numpy python-scipy python-matplotlib cython python-pip gfortran liblapack-dev
install: "pip install kabuki"
script: nosetests
